### ISSUE TITLE
treeData初始化时的bug

### ISSUE THREAD

**Issue by suguoyao** [Summer-Lin/vue-tree#1]
比如在初始化数据treeData中，父节点0下有子节点1，2，3，已经设置了0和1，初始化后父节点应该显示横杆半选状态以及子节点1的选中状态，但是现在显示的是0，1，2，3全选中了

**Comment by Summer-Lin** [comment]
按照你的描述，因为设置了0被选中，,0是父节点，所以子节点1 2 3 肯定会被选中的。
或者你提供一下数据。我这边调试下？

**Comment by suguoyao** [comment]
> 按照你的描述，因为设置了0被选中，,0是父节点，所以子节点1 2 3 肯定会被选中的。
> 或者你提供一下数据。我这边调试下？

你试试初始化时为 [1, 39, 41]

**Comment by Summer-Lin** [comment]
当时写的时候，因为后台只能让我提交最后一个子节点（也就是没有子节点的节点）。
所以我赋值的时候，只能赋值最后一个子节点。也就是41。
如果当赋值了1，那自然其他都会被选中。
非常感谢指教！
![image](https://user-images.githubusercontent.com/26006995/50808547-04bc7000-133a-11e9-9fc1-75754d910c8a.png)

**Comment by suguoyao** [comment]
> 当时写的时候，因为后台只能让我提交最后一个子节点（也就是没有子节点的节点）。
> 所以我赋值的时候，只能赋值最后一个子节点。也就是41。
> 如果当赋值了1，那自然其他都会被选中。
> 非常感谢指教！
> ![image](https://user-images.githubusercontent.com/26006995/50808547-04bc7000-133a-11e9-9fc1-75754d910c8a.png)

哈哈 客气了 我的后台和你相反，只选中了子节点，相关的父节点id也得传给后台
